const key = '@@react-redux-form-lite/';

export const REGISTER_FORM = `${key}REGISTER_FORM`;
export const REGISTER_FIELD = `${key}REGISTER_FIELD`;
export const CHANGE = `${key}CHANGE`;
export const BLUR = `${key}BLUR`;
export const FOCUS = `${key}FOCUS`;
export const ARRAY_PUSH = `${key}ARRAY_PUSH`;
export const UPDATE_VALIDATE_MESSAGE = `${key}UPDATE_VALIDATE_MESSAGE`;
export const UPDATE_VALIDATE_MESSAGES = `${key}UPDATE_VALIDATE_MESSAGES`;
export const UPDATE_WARNING_MESSAGE = `${key}UPDATE_WARNING_MESSAGE`;
export const UPDATE_WARNING_MESSAGES = `${key}UPDATE_WARNING_MESSAGES`;
export const UPDATE_VALIDATE_AND_WARNING_MESSAGES = `${key}UPDATE_VALIDATE_AND_WARNING_MESSAGES`;
export const CHANGE_SUBMITTED = `${key}CHANGE_SUBMITTED`;
export const UPDATE_FORM_STATE = `${key}UPDATE_FORM_STATE`;
export const REMOVE_FIELD = `${key}REMOVE_FIELD`;
export const REMOVE_FORM = `${key}REMOVE_FORM`;
export const RESET_FORM = `${key}RESET_FORM`;
export const SET_INITIAL_VALUES = `${key}SET_INITIAL_VALUES`;
